(load "stdlib.scm")

(def assert (lambda (name cond)
  (if cond
    (print "PASS" name)
    (error (join (list "FAIL:" name) " ")))))

; ── stdlib type predicates ────────────────────────────────────────────────────
(assert "list? true"  (list? '(a b)))
(assert "list? empty" (list? '()))
(assert "vec? true"   (vec? (vec 1 2)))
(assert "vec? scalar" (vec? 42))
(assert "string? true" (string? "hi"))
(assert "lambda? true" (lambda? (lambda (x) x)))
(assert "proc? true"   (proc? +))
(assert "fn? lambda"   (fn? map))
(assert "fn? proc"     (fn? +))
(assert "not list?"    (not (list? (vec 1 2))))
(assert "not vec?"     (not (vec? '(a b))))
(assert "not string?"  (not (string? 12)))

; ── stdlib function helpers ───────────────────────────────────────────────────
(assert "identity" (= (identity 7) 7))
(assert "const"    (= ((const 9) 123) 9))
(assert "compose"  (= ((compose square (lambda (x) (+ x 1))) 4) 25))
(assert "flip"     (= ((flip -) 2 10) 8))
(assert "iterate"  (= (iterate (lambda (x) (+ x 2)) 4 0) 8))

; ── list construction/access ──────────────────────────────────────────────────
(assert "iota len"   (= (len (iota 5)) 5))
(assert "iota first" (= (nth (iota 5) 0) 0))
(assert "iota last"  (= (nth (iota 5) 4) 4))
(assert "iota zero"  (= (len (iota 0)) 0))
(assert "range len"   (= (len (range 3 7)) 4))
(assert "range first" (= (nth (range 3 7) 0) 3))
(assert "range last"  (= (nth (range 3 7) 3) 6))
(assert "replicate len" (= (len (replicate 4 8)) 4))
(assert "replicate val" (= (nth (replicate 4 8) 2) 8))

(def l5 (list 10 20 30 40 50))
(assert "second" (= (second l5) 20))
(assert "third"  (= (third l5) 30))
(assert "last"   (= (last l5) 50))
(assert "init len"  (= (len (init l5)) 4))
(assert "init last" (= (last (init l5)) 40))

; ── list transforms ───────────────────────────────────────────────────────────
(assert "map len"   (= (len (map (lambda (x) (+ x 1)) '(0 1 2))) 3))
(assert "map val"   (= (nth (map square '(1 2 3)) 2) 9))
(assert "map empty" (= (len (map square '())) 0))
(assert "map str"   (= (join (map str '(1 2 3)) ",") "[1],[2],[3]"))
(assert "filter len"   (= (len (filter (lambda (x) (> x 2)) '(1 2 3 4))) 2))
(assert "filter first" (= (head (filter (lambda (x) (> x 2)) '(1 2 3 4))) 3))
(assert "filter empty" (= (len (filter (lambda (x) (> x 9)) '(1 2 3))) 0))
(assert "reduce sum"   (= (reduce + 0 '(1 2 3 4)) 10))
(assert "reduce prod"  (= (reduce * 1 '(1 2 3 4)) 24))
(assert "reduce empty" (= (reduce + 0 '()) 0))
(assert "reduce build" (= (join (reduce (lambda (acc x) (append acc (list (str x)))) '() '(1 2 3)) "") "[1][2][3]"))
(assert "flat-map len" (= (len (flat-map (lambda (x) (list x x)) '(1 2 3))) 6))
(assert "flat-map val" (= (nth (flat-map (lambda (x) (list x x)) '(1 2 3)) 3) 2))

; ── predicates ────────────────────────────────────────────────────────────────
(assert "any true"  (= (any (lambda (x) (> x 3)) '(1 2 3 4)) 1))
(assert "any false" (= (any (lambda (x) (> x 9)) '(1 2 3 4)) 0))
(assert "any empty" (= (any (lambda (x) 1) '()) 0))
(assert "all true"  (= (all (lambda (x) (> x 0)) '(1 2 3)) 1))
(assert "all false" (= (all (lambda (x) (> x 2)) '(1 2 3)) 0))
(assert "all empty" (= (all (lambda (x) 0) '()) 1))
(assert "member? num yes" (= (member? 3 '(1 2 3 4)) 1))
(assert "member? num no"  (= (member? 9 '(1 2 3 4)) 0))
(assert "member? str yes" (= (member? "b" '("a" "b" "c")) 1))
(assert "count" (= (count (lambda (x) (> x 2)) '(1 2 3 4 5)) 3))

; ── list restructuring/search ─────────────────────────────────────────────────
(assert "reverse-list" (= (head (reverse-list '(1 2 3))) 3))
(assert "list-take"    (= (join (map str (list-take 3 '(1 2 3 4 5))) ",") "[1],[2],[3]"))
(assert "list-drop"    (= (head (list-drop 2 '(1 2 3 4))) 3))
(assert "take-while"   (= (len (take-while (lambda (x) (< x 4)) '(1 2 3 4 5))) 3))
(assert "drop-while"   (= (head (drop-while (lambda (x) (< x 3)) '(1 2 3 4))) 3))
(assert "zip len"      (= (len (zip '(1 2 3) '(4 5 6))) 3))
(assert "zip-with"     (= (nth (zip-with + '(1 2 3) '(4 5 6)) 2) 9))
(assert "flatten"      (= (join (map str (flatten '((1 2) (3 (4)) 5))) ",") "[1],[2],[3],[4],[5]"))
(assert "partition yes len" (= (len (head (partition (lambda (x) (> x 2)) '(1 2 3 4)))) 2))
(assert "find"         (= (find (lambda (x) (> x 3)) '(1 2 3 4 5)) 4))
(assert "index-of"     (= (index-of (lambda (x) (= x 30)) '(10 20 30 40)) 2))

; ── assoc lists ───────────────────────────────────────────────────────────────
(def alist '((foo 10) (bar 20) (baz 30)))
(assert "assoc-get hit"  (= (assoc-get 'bar alist 0) 20))
(assert "assoc-get miss" (= (assoc-get 'qux alist 99) 99))

; ── core polymorphic sequence ops ────────────────────────────────────────────
(assert "append list"   (= (len (append '(1 2) '(3 4))) 4))
(assert "append string" (= (append "ab" "cd") "abcd"))
(assert "append vec"    (= (sum (append (vec 1 2) (vec 3 4))) 10))
(assert "reverse string" (= (reverse "abc") "cba"))
(assert "reverse list"   (= (head (reverse '(1 2 3))) 3))
(assert "reverse vec"    (= (nth (reverse (vec 1 2 3)) 0) 3))
(assert "slice string"   (= (slice "hello" 1 4) "ell"))
(assert "slice list"     (= (head (slice '(10 20 30 40) 1 3)) 20))
(assert "slice vec"      (= (sum (slice (vec 1 2 3 4) 1 3)) 5))
(assert "take vec"       (= (nth (take (vec 1 2 3) 5) 4) 0))
(assert "repeat vec"     (= (nth (repeat (vec 1 2 3) 8) 6) 1))
(assert "null list"      (= (null? '()) 1))
(assert "null string"    (= (null? "") 1))
(assert "null vec"       (= (null? (vec)) 1))


; ── assoc / unique / field-values helpers ────────────────────────────────────
(def al '((name "oboe") (dyn "ff") (pitch "A#3")))
(assert "assoc key" (= (head (assoc 'dyn al)) 'dyn))
(assert "assoc val" (= (second (assoc 'dyn al)) "ff"))
(assert "third helper" (= (third '(10 20 30 40)) 30))
(assert "sort-strings identity len" (= (len (sort-strings '("b" "a" "b"))) 3))
(assert "uniq-sorted len" (= (len (uniq-sorted '("b" "a" "b"))) 2))
(assert "sort-uniq len" (= (len (sort-uniq '("ob" "cl" "ob" "fl"))) 3))
(def entries '(((instrument "ob") (pitch "A#3"))
               ((instrument "cl") (pitch "B3"))
               ((instrument "ob") (pitch "C4"))))
(assert "field-values len" (= (len (field-values entries 'instrument)) 3))
(assert "field-values first" (= (head (field-values entries 'instrument)) "ob"))

(print "")
(print "all tests passed")
