(((time (vec 0))
 (length (vec 4.17786))
 (midi (vec 55))
 (style "ord")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A#3-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-B3-ff.wav")
)
)
 ((time (vec 6.15934))
 (length (vec 2.79814))
 (midi (vec 55))
 (style "ord")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A#3-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-B3-ff.wav")
)
)
 ((time (vec 8.99258))
 (length (vec 3.02677))
 (midi (vec 69))
 (style "ord")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A4-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-A4-pp.wav")
)
)
 ((time (vec 11.8838))
 (length (vec 2.69455))
 (midi (vec 67))
 (style "ord")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G4-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-G4-pp.wav")
)
)
 ((time (vec 14.9315))
 (length (vec 1.68037))
 (midi (vec 48))
 (style "ord")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A#3-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-B3-ff.wav")
)
)
 ((time (vec 16.1946))
 (length (vec 1.50377))
 (midi (vec 75))
 (style "ord")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#5-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 17.3547))
 (length (vec 1.32443))
 (midi (vec 78))
 (style "ord")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-F#5-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-F#5-pp.wav")
)
)
 ((time (vec 18.4444))
 (length (vec 0.928303))
 (midi (vec 93))
 (style "ord")
 (dynamic "f")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 19.3068))
 (length (vec 0.886174))
 (midi (vec 91))
 (style "ord")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 20.0265))
 (length (vec 1.10283))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 20.9193))
 (length (vec 1.08558))
 (midi (vec 79))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G5-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G5-pp.wav")
)
)
 ((time (vec 21.4196))
 (length (vec 0.974036))
 (midi (vec 75))
 (style "pizz")
 (dynamic "fff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#5-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 21.9065))
 (length (vec 0.870026))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-D#6-ff-2c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-D#6-ff-1c.wav")
)
)
 ((time (vec 22.4897))
 (length (vec 0.943283))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 23.1061))
 (length (vec 1.04447))
 (midi (vec 85))
 (style "pizz")
 (dynamic "f")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/sforzando/ClBb-sfz-C#6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/sforzando/Bn-sfz-C#5-f.wav")
)
)
 ((time (vec 23.9939))
 (length (vec 1.13464))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-pp.wav")
)
)
 ((time (vec 24.7996))
 (length (vec 0.644245))
 (midi (vec 105))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/flatterzunge-high-register/ClBb-flatt_hi_register-C7-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 25.0174))
 (length (vec 0.653736))
 (midi (vec 81))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A5-mf-2c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A5-mf-2c.wav")
)
)
 ((time (vec 25.2013))
 (length (vec 0.544164))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-D#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-D#6-ff.wav")
)
)
 ((time (vec 25.4512))
 (length (vec 0.673932))
 (midi (vec 73))
 (style "pizz")
 (dynamic "fff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C#5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-C#5-pp.wav")
)
)
 ((time (vec 25.6538))
 (length (vec 0.580504))
 (midi (vec 75))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-D#5-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/artificial-harmonic/Cb-harm_artificial-D#5-mf-1c.wav")
)
)
 ((time (vec 25.9393))
 (length (vec 0.647798))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 26.2474))
 (length (vec 0.60619))
 (midi (vec 81))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-A5-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 26.5358))
 (length (vec 0.688052))
 (midi (vec 78))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-F#5-mf-3c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-F#5-ff-1c.wav")
)
)
 ((time (vec 26.7177))
 (length (vec 0.649712))
 (midi (vec 81))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A5-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-A5-ff.wav")
)
)
 ((time (vec 27.0728))
 (length (vec 0.519375))
 (midi (vec 81))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-A5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 27.3311))
 (length (vec 0.522907))
 (midi (vec 93))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-mf-1c.wav")
)
)
 ((time (vec 27.5165))
 (length (vec 0.645235))
 (midi (vec 79))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G5-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G5-pp.wav")
)
)
 ((time (vec 27.742))
 (length (vec 0.631719))
 (midi (vec 103))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/flatterzunge-high-register/ClBb-flatt_hi_register-C7-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 28.0595))
 (length (vec 0.515306))
 (midi (vec 78))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-F#5-mf-3c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-F#5-mf-1c.wav")
)
)
 ((time (vec 28.429))
 (length (vec 0.55102))
 (midi (vec 85))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-mf.wav")
)
)
 ((time (vec 28.6231))
 (length (vec 0.661155))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-F#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 28.8143))
 (length (vec 0.615363))
 (midi (vec 96))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C7-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C7-ff-1c.wav")
)
)
 ((time (vec 29.1149))
 (length (vec 0.614065))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C6-mf.wav")
)
)
 ((time (vec 29.3561))
 (length (vec 0.659618))
 (midi (vec 84))
 (style "pizz")
 (dynamic "fff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 29.5884))
 (length (vec 0.625914))
 (midi (vec 78))
 (style "pizz")
 (dynamic "f")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/sforzando/Vn-sfz-F#5-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/sforzando/Va-sfz-F#5-f.wav")
)
)
 ((time (vec 29.8896))
 (length (vec 0.510434))
 (midi (vec 81))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-A5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-A5-ff.wav")
)
)
 ((time (vec 30.0801))
 (length (vec 0.531883))
 (midi (vec 93))
 (style "pizz")
 (dynamic "fff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/sforzando/ClBb-sfz-A6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 30.1897))
 (length (vec 0.574363))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/artificial-harmonic/Vc-harm_artificial-C#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/artificial-harmonic/Cb-harm_artificial-C#6-mf-1c.wav")
)
)
 ((time (vec 30.3146))
 (length (vec 0.520537))
 (midi (vec 87))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-D#6-pp-2c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-D#6-ff-1c.wav")
)
)
 ((time (vec 30.4264))
 (length (vec 0.526791))
 (midi (vec 85))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-ff.wav")
)
)
 ((time (vec 30.5455))
 (length (vec 0.523638))
 (midi (vec 91))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/ordinario/Hn-ord-F5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario/Tbn-ord-C5-mf.wav")
)
)
 ((time (vec 30.6556))
 (length (vec 0.56399))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 30.7978))
 (length (vec 0.476747))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/artificial-harmonic/Vc-harm_artificial-C#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/artificial-harmonic/Cb-harm_artificial-C#6-mf-1c.wav")
)
)
 ((time (vec 30.8987))
 (length (vec 0.564591))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 31.0231))
 (length (vec 0.551984))
 (midi (vec 93))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/note-lasting/Ob-lasting_one_sec-A6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-A6-mf.wav")
)
)
 ((time (vec 31.1578))
 (length (vec 0.542406))
 (midi (vec 90))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/ordinario/Hn-ord-F5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-p.wav")
)
)
 ((time (vec 31.2738))
 (length (vec 0.510333))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-F#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 31.3843))
 (length (vec 0.446729))
 (midi (vec 84))
 (style "pizz")
 (dynamic "f")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/sforzando/Vc-sfz-E5-f-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/sforzando/Cb-sfz-F#4-f-1c.wav")
)
)
 ((time (vec 31.5066))
 (length (vec 0.533379))
 (midi (vec 91))
 (style "pizz")
 (dynamic "f")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/sforzando/Vn-sfz-G6-f-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/sforzando/Va-sfz-G6-f.wav")
)
)
 ((time (vec 31.6248))
 (length (vec 0.487727))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-pp.wav")
)
)
 ((time (vec 31.7442))
 (length (vec 0.513305))
 (midi (vec 93))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/ordinario/Hn-ord-F5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-p.wav")
)
)
 ((time (vec 31.8505))
 (length (vec 0.535004))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 31.9671))
 (length (vec 0.427691))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-C6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/ordinario/Cb-ord-C5-ff-1c.wav")
)
)
 ((time (vec 32.0999))
 (length (vec 0.510201))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 32.2024))
 (length (vec 0.52795))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C6-mf.wav")
)
)
 ((time (vec 32.3209))
 (length (vec 0.523442))
 (midi (vec 91))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/ordinario/Hn-ord-F5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-p.wav")
)
)
 ((time (vec 32.4286))
 (length (vec 0.53153))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 32.5568))
 (length (vec 0.534671))
 (midi (vec 85))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/artificial-harmonic/Vc-harm_artificial-C#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/artificial-harmonic/Cb-harm_artificial-C#6-mf-1c.wav")
)
)
 ((time (vec 32.6888))
 (length (vec 0.483741))
 (midi (vec 90))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-F#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-F#6-mf-1c.wav")
)
)
 ((time (vec 32.7973))
 (length (vec 0.522531))
 (midi (vec 85))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-mf.wav")
)
)
 ((time (vec 32.9059))
 (length (vec 0.573524))
 (midi (vec 90))
 (style "pizz")
 (dynamic "f")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/sforzando/Hn-sfz-D5-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-f.wav")
)
)
 ((time (vec 33.0406))
 (length (vec 0.454377))
 (midi (vec 91))
 (style "pizz")
 (dynamic "f")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/sforzando/ClBb-sfz-G6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/sforzando/Bn-sfz-C#5-f.wav")
)
)
 ((time (vec 33.159))
 (length (vec 0.536125))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-C6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/ordinario/Cb-ord-C5-ff-1c.wav")
)
)
 ((time (vec 33.2612))
 (length (vec 0.481218))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C6-mf-1c.wav")
)
)
 ((time (vec 33.3889))
 (length (vec 0.446816))
 (midi (vec 90))
 (style "pizz")
 (dynamic "f")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/sforzando/Ob-sfz-F#6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/sforzando/Fl-sfz-F#6-f.wav")
)
)
 ((time (vec 33.492))
 (length (vec 0.537912))
 (midi (vec 84))
 (style "pizz")
 (dynamic "f")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/sforzando/Hn-sfz-D5-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-f.wav")
)
)
 ((time (vec 33.6132))
 (length (vec 0.449468))
 (midi (vec 91))
 (style "pizz")
 (dynamic "fff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 33.7512))
 (length (vec 0.459651))
 (midi (vec 87))
 (style "pizz")
 (dynamic "f")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/sforzando/Vn-sfz-D#6-f-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/sforzando/Va-sfz-D#6-f.wav")
)
)
 ((time (vec 33.8795))
 (length (vec 0.462246))
 (midi (vec 87))
 (style "pizz")
 (dynamic "f")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/sforzando/Ob-sfz-D#6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/sforzando/Fl-sfz-D#6-f.wav")
)
)
 ((time (vec 33.9906))
 (length (vec 0.527819))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-C6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/ordinario/Cb-ord-C5-ff-1c.wav")
)
)
 ((time (vec 34.1146))
 (length (vec 0.450629))
 (midi (vec 93))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/flatterzunge-high-register/ClBb-flatt_hi_register-A6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 34.2382))
 (length (vec 0.572782))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C#6-pp-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C#6-ff-2c.wav")
)
)
 ((time (vec 34.354))
 (length (vec 0.449131))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C6-mf.wav")
)
)
 ((time (vec 34.4606))
 (length (vec 0.494705))
 (midi (vec 91))
 (style "pizz")
 (dynamic "f")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/sforzando/Hn-sfz-D5-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-f.wav")
)
)
 ((time (vec 34.573))
 (length (vec 0.491623))
 (midi (vec 91))
 (style "pizz")
 (dynamic "mf")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-mf.wav")
)
)
 ((time (vec 34.6937))
 (length (vec 0.445158))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-C6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/ordinario/Cb-ord-C5-ff-1c.wav")
)
)
 ((time (vec 34.8327))
 (length (vec 0.552415))
 (midi (vec 93))
 (style "pizz")
 (dynamic "f")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/sforzando/Ob-sfz-F#6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/sforzando/Fl-sfz-A6-f.wav")
)
)
 ((time (vec 34.9535))
 (length (vec 0.458487))
 (midi (vec 84))
 (style "pizz")
 (dynamic "f")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/sforzando/Vn-sfz-C6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/sforzando/Va-sfz-C6-f-1c.wav")
)
)
 ((time (vec 35.085))
 (length (vec 0.44591))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 35.1878))
 (length (vec 0.502361))
 (midi (vec 85))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/artificial-harmonic/Vc-harm_artificial-C#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/artificial-harmonic/Cb-harm_artificial-C#6-mf-1c.wav")
)
)
 ((time (vec 35.3227))
 (length (vec 0.572249))
 (midi (vec 91))
 (style "pizz")
 (dynamic "f")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/sforzando/Hn-sfz-D5-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-f.wav")
)
)
 ((time (vec 35.4314))
 (length (vec 0.565517))
 (midi (vec 84))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C6-mf.wav")
)
)
 ((time (vec 35.5521))
 (length (vec 0.49935))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ff")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-F#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-ff.wav")
)
)
 ((time (vec 35.689))
 (length (vec 0.49921))
 (midi (vec 85))
 (style "pizz")
 (dynamic "mf")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C#6-mf-2c.wav")
)
)
 ((time (vec 35.7963))
 (length (vec 0.439104))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ff")
 (instruments ("Vc" "Cb")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violoncello/ordinario/Vc-ord-C6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Contrabass/ordinario/Cb-ord-C5-ff-1c.wav")
)
)
 ((time (vec 35.8974))
 (length (vec 0.433948))
 (midi (vec 84))
 (style "pizz")
 (dynamic "fff")
 (instruments ("Hn" "Tbn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Horn/ordinario/Hn-ord-F5-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Brass/Trombone/ordinario-no-mouthpiece/Tbn-no_mouthpiece-F5-p.wav")
)
)
 ((time (vec 36.0223))
 (length (vec 0.228566))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-D#6-pp.wav")
)
)
 ((time (vec 36.123))
 (length (vec 0.179997))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 36.2237))
 (length (vec 0.172414))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-F#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-F#6-mf-1c.wav")
)
)
 ((time (vec 36.3136))
 (length (vec 0.19179))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 36.4095))
 (length (vec 0.178749))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 36.5073))
 (length (vec 0.190066))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 36.5981))
 (length (vec 0.190906))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 36.689))
 (length (vec 0.198996))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-D#6-pp-2c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-D#6-ff-1c.wav")
)
)
 ((time (vec 36.7804))
 (length (vec 0.204677))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-D#6-pp.wav")
)
)
 ((time (vec 36.8804))
 (length (vec 0.222617))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-G6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 36.9757))
 (length (vec 0.180492))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 37.0706))
 (length (vec 0.225383))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-F#6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-F#6-ff.wav")
)
)
 ((time (vec 37.1753))
 (length (vec 0.218426))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 37.2711))
 (length (vec 0.205356))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C6-mf-1c.wav")
)
)
 ((time (vec 37.3746))
 (length (vec 0.228928))
 (midi (vec 85))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-pp.wav")
)
)
 ((time (vec 37.4668))
 (length (vec 0.22937))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 37.5589))
 (length (vec 0.189859))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-F#6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-F#6-mf-1c.wav")
)
)
 ((time (vec 37.662))
 (length (vec 0.180724))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-F#6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-F#6-ff.wav")
)
)
 ((time (vec 37.7521))
 (length (vec 0.183273))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 37.8416))
 (length (vec 0.195214))
 (midi (vec 85))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C#6-pp-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C#6-ff-2c.wav")
)
)
 ((time (vec 37.9432))
 (length (vec 0.223195))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-D#6-pp.wav")
)
)
 ((time (vec 38.0435))
 (length (vec 0.197982))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 38.1466))
 (length (vec 0.187096))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C6-mf-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C6-mf-1c.wav")
)
)
 ((time (vec 38.2551))
 (length (vec 0.229236))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 38.357))
 (length (vec 0.202599))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 38.4485))
 (length (vec 0.195087))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 38.5523))
 (length (vec 0.21107))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-D#6-pp.wav")
)
)
 ((time (vec 38.6425))
 (length (vec 0.191228))
 (midi (vec 87))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-D#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 38.7407))
 (length (vec 0.172014))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 38.8366))
 (length (vec 0.228561))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 38.9379))
 (length (vec 0.225467))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-F#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 39.0467))
 (length (vec 0.196808))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
 ((time (vec 39.1365))
 (length (vec 0.214279))
 (midi (vec 91))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-G6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-G6-ff.wav")
)
)
 ((time (vec 39.2259))
 (length (vec 0.17865))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-C6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 39.3231))
 (length (vec 0.213623))
 (midi (vec 85))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-C#6-pp-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-C#6-ff-2c.wav")
)
)
 ((time (vec 39.4285))
 (length (vec 0.197628))
 (midi (vec 84))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C6-pp.wav")
)
)
 ((time (vec 39.5232))
 (length (vec 0.18939))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/ordinario/ClBb-ord-F#6-ff.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 39.6273))
 (length (vec 0.178491))
 (midi (vec 85))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-C#6-pp.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-C#6-pp.wav")
)
)
 ((time (vec 39.7166))
 (length (vec 0.225219))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("ClBb" "Bn")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Clarinet-Bb/sforzando/ClBb-sfz-A6-f.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Bassoon/ordinario/Bn-ord-D#5-pp.wav")
)
)
 ((time (vec 39.8195))
 (length (vec 0.187907))
 (midi (vec 90))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Ob" "Fl")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Oboe/ordinario/Ob-ord-F#6-mf.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Winds/Flute/ordinario/Fl-ord-F#6-ff.wav")
)
)
 ((time (vec 39.9128))
 (length (vec 0.178928))
 (midi (vec 93))
 (style "pizz")
 (dynamic "ppp")
 (instruments ("Vn" "Va")
)
 (paths ("/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Violin/ordinario/Vn-ord-A6-ff-1c.wav" "/Users/n4/Projects/Media/Datasets/StaticSOL/Strings/Viola/ordinario/Va-ord-A6-ff-1c.wav")
)
)
)
