(load "stdlib.scm")

; reference.scm — pure0 language reference (updated for current core)

; arithmetic
(print (+ 1 2 3 4))
(print (- 100 30 20))
(print (* 2 3 4))
(print (/ 100 4 5))
(print (- 7))
(print (pow 2 16))
(print (sqrt 2))
(print (log (exp 1)))
(print (floor 3.9))
(print (ceil 3.1))
(print (abs -99))
(print pi)
(print (sin pi))
(print (= 3 3))
(print (< 1 2))
(print (> 2 1))
(print (<= 2 2))
(print (>= 3 2))
(print (not 0))
(print (not 5))

; vectors
(def v (vec 1 2 3 4 5))
(print (+ v 10))
(print (* v 2))
(print (* v v))
(print (+ (vec 1 2 3) (vec 10 20 30)))
(print (zeros 4))
(print (ones 3))
(print (linspace 0 1 5))
(print (rand 4))
(print (nth v 0))
(print (nth v 4))
(print (slice v 1 4))
(print (append (vec 1 2) (vec 3 4)))
(print (reverse v))
(print (sort (vec 3 1 4 1 5 9 2)))
(print (len v))
(print (take (vec 1 2 3 4) 2))
(print (take (vec 1 2 3) 5))
(print (repeat (vec 1 2 3) 8))
(print (sum v))
(print (prod v))
(print (min v))
(print (max v))
(print (mean v))
(def ns (linspace 1 8 8))
(print (* ns ns))

; lists
(def colors '(red green blue))
(def nums (list (+ 1 0) (+ 1 1) (+ 1 2)))
(print (head nums))
(print (tail nums))
(print (null? '()))
(print (null? nums))
(print (cons 0 nums))
(print (cons 'x '(y z)))
(print (append '(a b) '(c d)))
(print (append nums (list 4 5)))
(print (iota 5))
(print (range 3 7))
(print (replicate 4 0))
(def l5 (list 10 20 30 40 50))
(print (second l5))
(print (third l5))
(print (last l5))
(print (init l5))
(print (len colors))
(print (nth colors 0))
(print '(+ 1 2))
(print (eval '(+ 1 2)))
(print (map square '(1 2 3 4)))
(print (filter (lambda (x) (> x 2)) '(1 2 3 4 5)))
(print (reduce + 0 '(1 2 3 4 5)))
(print (flat-map (lambda (x) (list x x)) '(1 2 3)))

; strings
(def greeting "hello, world")
(print (len greeting))
(print (nth greeting 0))
(print (slice greeting 0 5))
(print (reverse greeting))
(print (append "hello" " world"))
(print (str (vec 1 2 3)))
(print (str '(a b c)))
(print (num "2.718"))
(print (match "pure0 is cool" "cool"))
(print (match "pure0 is cool" "^is"))
(print (match "abc123" "[0-9]+"))
(def parts (split "one,two,three" ","))
(print parts)
(print (join parts " | "))
(print (join (list "x=" (str 42)) ""))
(print (starts-with? "hello world" "hello"))
(print (ends-with? "hello world" "world"))
(print (starts-with? "hello world" "world"))

; types
(print (type 42))
(print (type (vec 1 2)))
(print (type "hi"))
(print (type '(a b)))
(print (type +))
(print (type (lambda (x) x)))
(print (vec? v))
(print (list? colors))
(print (string? greeting))
(print (proc? +))
(print (lambda? map))
(print (fn? reduce))

; closures / partial application
(def make-adder (lambda (n) (lambda (x) (+ x n))))
(def add10 (make-adder 10))
(print (add10 5))
(def add (lambda (a b) (+ a b)))
(def inc (add 1))
(print (inc 41))
(def clamp01 (clamp 0 1))
(print (clamp01 -0.5))
(print (clamp01 0.7))
(print (clamp01 1.3))
(print (map (add 5) (iota 5)))
